services:
  Shopping\ApiTKManipulationBundle\ParamConverter\PayloadConverter:
    autowire: true
    public: false
    tags:
      - { name: request.param_converter, priority: 1 } # needs to run before doctrine converter

  Shopping\ApiTKManipulationBundle\ParamConverter\DeleteConverter:
    autowire: true
    public: false
    tags:
    - { name: request.param_converter, priority: 1 } # needs to run before doctrine converter

  Shopping\ApiTKManipulationBundle\Describer\PayloadAnnotationDescriber:
    autowire: true
    public: false
    arguments:
      - '@nelmio_api_doc.routes.default'
    tags:
      - { name: 'nelmio_api_doc.route_describer', priority: -1000 }

  Shopping\ApiTKManipulationBundle\Describer\DeleteAnnotationDescriber:
    autowire: true
    public: false
    arguments:
      - '@nelmio_api_doc.routes.default'
    tags:
      - { name: 'nelmio_api_doc.route_describer', priority: -1000 }
